[package]
name = "tarifa-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
description = "Command-line interface for Tarifa alpha model"

[lints]
workspace = true

[[bin]]
name = "tarifa"
path = "src/main.rs"

[dependencies]
tarifa-traits.workspace = true
factors.workspace = true
tarifa-combine.workspace = true
tarifa-eval.workspace = true

perth-data.workspace = true

polars.workspace = true
ndarray.workspace = true
chrono.workspace = true
clap.workspace = true
tokio.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
